<?php

/**
 * Разработал Максим Руденко
 * email: rudenko.programmer@gmail.com
 * Дата: 30.09.2017
 */

namespace common\widgets;

use yii\base\Widget;

class CTMenuWidget extends Widget
{
    public $items;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run(){
        $items = $this->items;
        return $this->render('menu-widget', compact('items'));
    }
}